Repository roihunter/gold-digger, pull requests merged in 2018-09, with the labels that each got.

#41 Fix Fixer - get supported currencies
  gold_digger/data_providers/fixer.py
Labels: waiting-review-dave, waiting-review-jiri

#42 Separate Cron update for fixer
  gold_digger/__main__.py
  gold_digger/di.py
  gold_digger/managers/exchange_rate_manager.py
  tests/test_exchange_rate_manager.py
Labels: bug, waiting-review-dave, waiting-review-miso, waiting-review-roman

#43 Rename Jenkins scripts
  jenkins/pipeline/deploy-master.groovy
  jenkins/pipeline/multifunctional.groovy
Labels: waiting-review-dave, waiting-review-mato, waiting-review-miso, waiting-review-roman
