Repository roihunter/gold-digger, pull requests merged in 2018-11, with the labels that each got.

#50 Fixes GrandTrunk provider
  gold_digger/data_providers/grandtrunk.py
Labels: bug, waiting-review-dave, waiting-review-jiri, waiting-review-mato, waiting-review-miso, waiting-review-roman

#49 Fix yahoo provider, #26540
  README.md
  gold_digger/__main__.py
  gold_digger/data_providers/yahoo.py
  gold_digger/di.py
  kubernetes/gold-digger-cron-deployment.yaml
  kubernetes/gold-digger-deployment.yaml
  kubernetes/gold-digger-service.yaml
  tests/data_providers/conftest.py
  tests/data_providers/test_yahoo.py
Labels: waiting-review-dave, waiting-review-jiri, waiting-review-mato, waiting-review-miso, waiting-review-roman

#54 Gunicorn logging to graylog
  Dockerfile
  gold_digger/di.py
  gold_digger/settings/settings_gunicorn.py
  gunicorn_logging_master
  kubernetes/gold-digger-cron-deployment.yaml
  kubernetes/gold-digger-deployment.yaml
Labels: waiting-review-dave, waiting-review-mato, waiting-review-miso, waiting-review-roman

#55 Update gunicorn settings across documentations
  Dockerfile
  README.md
  gold_digger/__main__.py
  gold_digger/settings/settings_gunicorn.py
Labels: waiting-review-dave, waiting-review-jozo, waiting-review-mato, waiting-review-miso, waiting-review-roman
