Repository roihunter/gold-digger, pull requests merged in 2019-04, with the labels that each got.

#62 Fix conversion rate for Fixer and Unicredit provider, #28279
  gold_digger/data_providers/__init__.py
  gold_digger/data_providers/_provider.py
  gold_digger/data_providers/fixer.py
  gold_digger/data_providers/unicredit.py
  gold_digger/di.py
  tests/data_providers/conftest.py
  tests/data_providers/test_fixer.py
Labels: bug, waiting-review-mato, waiting-review-miso, waiting-review-roman

#65 Cache supported currencies of Rates API provider.
  gold_digger/data_providers/rates_api.py
Labels: bug

#66 Upgdate packages urllib3 and SQLAlchemy #28499 #28543
  Pipfile
  Pipfile.lock
Labels: easy-review
